### ISSUE TITLE
TypeError: ufunc 'matmul' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by xinyeCH** [thejarlid/VideoStabilizationPy#2]
I got a error when runing the code? How can I solve the problem? thanks!
bug report:
Traceback (most recent call last):
  File "/Users/yexin/Downloads/test_vstab/video_stabilization.py", line 385, in <module>
    main()
  File "/Users/yexin/Downloads/test_vstab/video_stabilization.py", line 379, in main
    smooth_path = compute_smooth_path(original_frames[0].shape, timewise_homographies)
  File "/Users/yexin/Downloads/test_vstab/video_stabilization.py", line 229, in compute_smooth_path
    residual_t = np.transpose(timewise_homographies[i + 1]) @ B_t1 - B_t
TypeError: ufunc 'matmul' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by thejarlid** [comment]
residual computation should now be fixed
